version: "3"

services:
  api:
    build: apps/web-api
    env_file: apps/web-api/.env
    container_name: web-api-terraform
    ports:
      - "3001:3001"
    depends_on:
      - login
    networks:
      - local_network
  login:
    build: apps/login-service
    env_file: apps/login-service/.env
    container_name: login-service-terraform
    ports:
      - "3002:3002"
    networks:
      - local_network
networks:
  local_network:
    driver: bridge